# MongoDB connection
mongodb.url=mongodb://127.0.0.1:27017/ycsb?w=1

# Custom workload
workload=site.ycsb.workloads.CoreWorkload

# Dataset size
recordcount=100000
operationcount=200000

# Field configuration
fieldcount=10
fieldlength=100

# Workload behavior
requestdistribution=uniform

# Required properties
readallfields=true
writeallfields=true